name: Python Web Monitor & Scraper

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Minden óra 0. percében lefut

jobs:
  build:
    runs-on: ubuntu-latest
    # Engedélyt adunk a robotnak, hogy módosítsa a fájlokat (írja a README-t)
    permissions:
      contents: write

    steps:
    - name: Repo letöltése
      uses: actions/checkout@v4

    - name: Python beállítása
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Függőségek telepítése
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   # - name: Tesztek futtatása
   #   run: pytest test_kalkulator.py

    - name: Scraper futtatása és README frissítése
      run: python scraper.py

    - name: Változtatások visszaküldése a GitHubra
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        # Csak akkor commitol, ha valóban változott valami
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-frissítés: Trending projektek" && git push)
