name: Python CI Teszt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Könyvtárak telepítése
      run: pip install -r requirements.txt
    - name: Tesztek futtatása
      run: pytest test_kalkulator.py
